language: python
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install ./aiohttp
  - pip install pytest pytest-aiohttp pytest-cov

script:
  py.test --cov=aiohttp_jinja2_haggle aiohttp/test.py

env:
  matrix:
    - PYTHONASYNCIODEBUG=1
    - PYTHONASYNCIODEBUG=
